name: tienda

services:
  api1:
    image: sar-tienda-api:latest
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: tienda-api1
    env_file:
      - path: ./backend/.env
        required: false
    ports:
      - "${TIENDA_API1_PORT:-4557}:80"
    restart: unless-stopped
    networks:
      - tienda

  api2:
    image: sar-tienda-api:latest
    container_name: tienda-api2
    env_file:
      - path: ./backend/.env
        required: false
    depends_on:
      - api1
    ports:
      - "${TIENDA_API2_PORT:-4558}:80"
    restart: unless-stopped
    networks:
      - tienda

  api-nginx:
    image: sar-tienda-api-nginx:latest
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    container_name: tienda-api-nginx
    depends_on:
      - api1
      - api2
    ports:
      - "${TIENDA_API_PORT:-4555}:80"
    restart: unless-stopped
    networks:
      - tienda

  frontend:
    image: sar-tienda-frontend:latest
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_API_URI: "${TIENDA_VITE_API_URI:-http://192.168.8.16:4555/api/}"
        VITE_API_PUBLIC_URI: "${TIENDA_VITE_API_PUBLIC_URI:-http://192.168.8.16:4555/}"
        VITE_API_ENVIROMENT: "${TIENDA_VITE_API_ENVIROMENT:-PRODUCCION}"
    container_name: tienda-frontend
    depends_on:
      - api-nginx
    ports:
      - "${TIENDA_FRONTEND_PORT:-8007}:80"
    restart: unless-stopped
    networks:
      - tienda

networks:
  tienda:
    name: tienda-network
