<?php

namespace Database\Seeders;

use App\Models\Modelos;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ModelosSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */


    public function run() {
        Modelos::create(['hr' => 'HHFD1', 'ctrhr' => '-', 'ar' => '-', 'cantidad' => 5, 'descripcion' => '', 'codigo' =>        '71001-F0A71-C1', 'fila_id' => 1, 'nombre' =>    'SFEP', 'color_id' =>    1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HEFS1', 'ctrhr' => '-', 'ar' => '-', 'cantidad' => 10, 'descripcion' => 'MATERIAL: CUERO NEGRO LISO (con HEATER) HILO DECK: GM20W-18050-00 (cono amarillo)', 'codigo' =>    '71001-F0B21-C1', 'fila_id' => 1, 'nombre' =>    'SFKQ', 'color_id' =>    1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HEFS1', 'ctrhr' => '-', 'ar' => '-', 'cantidad' => 10, 'descripcion' => 'MATERIAL: CUERO NEGRO PERFORADO HILO DECK: GM20W-18050-00 (cono amarillo)', 'codigo' => '71001-F0B31-C1', 'fila_id' => 1, 'nombre' =>    'SFMR', 'color_id' =>    1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HHFD', 'ctrhr' => '-', 'ar' => '-', 'cantidad' => 10, 'descripcion' => 'MATERIAL', 'codigo' =>    '71001-F0D71-C1', 'fila_id' => 1, 'nombre' => 'SFHP', 'color_id' =>    1, 'material_id' =>    1, 'airbag' =>    1]);
        Modelos::create(['hr' => '-', 'ctrhr' => '	-', 'ar' => '-', 'cantidad' => 10, 'descripcion' => '', 'codigo' => '71001-F0M50-C0',   'fila_id' => 1, 'nombre' => 'SFPC', 'color_id' => 1, 'material_id' =>    4, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HEFS', 'ctrhr' => '-', 'ar' => '-', 'cantidad' => 10, 'descripcion' => '', 'codigo' => '71001-SS510-D0',  'fila_id' => 1, 'nombre' => 'SFGG-D0', 'activo' => 0, 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HACA', 'ctrhr' => '-', 'ar' => '-', 'cantidad' => 10, 'descripcion' => '', 'codigo' => '71001-YPA80-C0',  'fila_id' => 1, 'nombre' => 'SFNJ', 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HAAA', 'ctrhr' => '-', 'ar' => '-', 'cantidad' => 10, 'descripcion' => '', 'codigo' => '71001-YPC80-C0',  'fila_id' => 1, 'nombre' => 'SFNG', 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HEFD1', 'ctrhr' => '-', 'ar' => '-', 'cantidad' => 10, 'descripcion' => '', 'codigo' => '71001-YPQ40-C0', 'fila_id' => 1, 'nombre' => 'SFOR', 'activo' => 0, 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HHFS', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '71002-0KW30',  'fila_id' => 1, 'nombre' => 'SFHH', 'activo' => 0, 'color_id' => 2, 'material_id' => 1, 'airbag' => 0]);
        Modelos::create(['hr' => 'HEFE', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '71002-0KW50',  'fila_id' => 1, 'nombre' => 'SFEH', 'activo' => 0, 'color_id' => 2, 'material_id' => 5, 'airbag' => 0]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10,     'descripcion' => '', 'codigo' => '71003-0K440', 'fila_id' => 1, 'nombre' => 'SFPA', 'color_id' => 1, 'material_id' => 4, 'airbag' => 0]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10,     'descripcion' => '', 'codigo' => '71003-0K450', 'fila_id' => 1, 'nombre' => 'SFLA', 'color_id' => 1, 'material_id' => 2, 'airbag' => 0]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10,     'descripcion' => '', 'codigo' => '71003-0K470', 'fila_id' => 1, 'nombre' => 'SFLB', 'color_id' => 1, 'material_id' => 2, 'airbag' => 0]);
        Modelos::create(['hr' => 'HLFD', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '71003-0K480', 'fila_id' => 1, 'nombre' => 'SFLD', 'activo' => 0, 'color_id' => 1, 'material_id' => 2, 'airbag' => 0]);
        Modelos::create(['hr' => 'HHFD', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '71003-0K510', 'fila_id' => 1, 'nombre' => 'SFHF', 'activo' => 0, 'color_id' => 1, 'material_id' => 1, 'airbag' => 0]);
        Modelos::create(['hr' => 'HEFS', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '71003-0K530', 'fila_id' => 1, 'nombre' => 'SFEF', 'activo' => 0, 'color_id' => 1, 'material_id' => 5, 'airbag' => 0]);
        Modelos::create(['hr' => 'HEFS', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '71003-0K540', 'fila_id' => 1, 'nombre' => 'SFEG', 'activo' => 0, 'color_id' => 1, 'material_id' => 5, 'airbag' => 1]);
        Modelos::create(['hr' => 'HEFE', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '71003-0K560', 'fila_id' => 1, 'nombre' => 'SFEJ', 'activo' => 0, 'color_id' => 2, 'material_id' => 5, 'airbag' => 1]);
        Modelos::create(['hr' => 'HHFS', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '71003-0K600', 'fila_id' => 1, 'nombre' => 'SFHJ', 'color_id' => 2, 'material_id' => 1, 'airbag' => 1]);
        Modelos::create(['hr' => 'HHFS1', 'ctrhr' => '-', 'ar' => '	-', 'cantidad' =>    10, 'descripcion' => 'MATERIAL: TELA GRIS HILO DECK: GM20W-18050-00 (cono amarillo)', 'codigo' => '71003-0K600-C0', 'fila_id' => 1, 'nombre' => 'SFJJ', 'color_id' =>    4, 'material_id' =>    1, 'airbag' =>    1]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '	-', 'cantidad' =>    10,     'descripcion' => 'MATERIAL: TELA NEGRA', 'codigo' => '71003-0KT40', 'fila_id' => 1, 'nombre' => 'SFLC', 'color_id' =>    1, 'material_id' =>    2, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HLFD', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => 'MATERIAL: PVC NEGRO', 'codigo' => '71003-0KT50', 'fila_id' => 1, 'nombre' => 'SFLE', 'color_id' =>    1, 'material_id' =>    2, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HHFD', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '71003-0KT60', 'fila_id' => 1, 'nombre' => 'SFHG', 'color_id' =>    1, 'material_id' =>    1, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HEFE', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                                                                        'codigo' => '71003-0KV80', 'fila_id' => 1, 'nombre' => 'SFEN', 'color_id' =>    2, 'activo' => 0, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HEFS1', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => 'MATERIAL: CUERO NEGRO LISO HILO DECK: GM20W-18050-00 (cono amarillon)', 'codigo' => '71003-0KV81-C0', 'fila_id' => 1, 'nombre' => 'SFKN', 'color_id' =>    1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HEFE', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                                                                        'codigo' => '71003-0KW00', 'fila_id' => 1, 'nombre' => 'SFEK', 'activo' => 0, 'color_id' =>    2, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HBFE', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                                                                        'codigo' => '71003-0KW10', 'fila_id' => 1, 'nombre' => 'SFBN', 'color_id' =>    3, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10,     'descripcion' => '',                                                                        'codigo' => '71003-0KW90', 'fila_id' => 1, 'nombre' => 'SFPB', 'color_id' =>    1, 'material_id' =>    4, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HHFD', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                                                                        'codigo' => '71003-AR010', 'fila_id' => 1, 'nombre' => 'SFRF', 'activo' => 0, 'color_id' =>    1, 'material_id' =>    1, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HHFD1', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => 'MATERIAL: CUERO NEGRO PERFORADO HILO DECK: GM20W-18250-00 (cono negro)', 'codigo' => '71003-F0A81-C1', 'fila_id' => 1, 'nombre' => 'SFTS', 'color_id' =>    1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HEFS', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                                                                        'codigo' => '71003-PH540', 'fila_id' => 1, 'nombre' => 'SFTG', 'activo' => 0, 'color_id' =>    1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HEUS', 'ctrhr' => 'CEUS', 'ar' => 'AEUS', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '71005-0KM50', 'fila_id' => 2, 'nombre' => 'SUES', 'activo' => 0, 'color_id' =>    2, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HEUS1', 'ctrhr' => 'CEUS1', 'ar' => 'AEUS1', 'cantidad' =>    10, 'descripcion' => 'MATERIAL: CUERO NEGRO LISO HILO DECK: GM20W-18050-00 (cono amarillo)', 'codigo' =>    '71005-0KM52-C2', 'fila_id' => 2, 'nombre' =>    'SUKS', 'color_id' =>    1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HHUS', 'ctrhr' => 'CHUS', 'ar' => 'AHUS', 'cantidad' =>    10, 'descripcion' => '',                                                                        'codigo' => '71005-0KN00	   ', 'fila_id' => 2, 'nombre' => 'SUHS', 'activo' => 0,       'color_id' => 2, 'material_id' =>    1, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HHUS1', 'ctrhr' => 'CHUS1', 'ar' => 'AHUS1', 'cantidad' =>    10, 'descripcion' => 'MATERIAL: TELA GRIS HILO DECK: GM20W-18050-00 (cono amarillo)',                'codigo' => '71005-0KN01-C2', 'fila_id' => 2, 'nombre' =>    'SUJS',       'color_id' => 4, 'material_id' =>    1, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HBUS', 'ctrhr' => 'CBUS', 'ar' => 'ABUS', 'cantidad' =>          10, 'descripcion' => '',                                                            'codigo' => '71005-0KP10	   ', 'fila_id' => 2, 'nombre' => 'SUBS',       'color_id' => 3, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HEUS1', 'ctrhr' => 'CEUS1', 'ar' => 'AEUS1', 'cantidad' =>    10, 'descripcion' => 'MATERIAL: CUERO NEGRO PERFORADO HILO DECK: GM20W-18050-00 (cono amarillo)',    'codigo' => '71005-0KQ81-C2', 'fila_id' => 2, 'nombre' =>    'SUMS',       'color_id' => 1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HEUS1', 'ctrhr' => 'CEUS1', 'ar' => 'AEUS1', 'cantidad' =>    10, 'descripcion' => '',                                                                        'codigo' => '71005-YP140-C2', 'fila_id' => 3, 'nombre' =>    'SUNS',       'color_id' => 1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HESS', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                                                                            'codigo' => '71009-0KA20', 'fila_id' => 3, 'nombre' => 'SSES', 'activo' => 0,       'color_id' => 2, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HHSS', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                                                                            'codigo' => '71009-0KA40', 'fila_id' => 3, 'nombre' => 'SSHS', 'activo' => 0,       'color_id' => 2, 'material_id' =>    1, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HBSS', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                                                                        'codigo' => '71009-0KB00', 'fila_id' => 3, 'nombre' => 'SSBN',       'color_id' => 3, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HPSS1', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => 'MATERIAL: PVC NEGRO',                                                                'codigo' => '71009-0KB30-C1', 'fila_id' => 3, 'nombre' =>    'SSLN',       'color_id' => 1, 'material_id' =>    4, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HHSS1', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                                                                            'codigo' => '71009-0KD50-C1', 'fila_id' => 3, 'nombre' =>    'SSFN',       'color_id' => 4, 'material_id' =>    1, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HEFD1', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                                                                            'codigo' => '71071-YPL40-C0', 'fila_id' => 1, 'nombre' =>    'SFON', 'activo' => 0,       'color_id' => 1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>     10, 'descripcion' => '',                                                                        'codigo' => '71100-VR010', 'fila_id' => 5, 'nombre' => 'HFLD-R', 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>     10, 'descripcion' => '',                                                                        'codigo' => '71100-VR020', 'fila_id' => 5, 'nombre' => 'HFHF', 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>     20, 'descripcion' => '',                                                                        'codigo' => '71200-VR010', 'fila_id' => 5, 'nombre' => 'HFLD-L', 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HETD', 'ctrhr' => 'CETD', 'ar' => 'AETD', 'cantidad' =>    10, 'descripcion' => '',                        'codigo' => '79100-0KJ80', 'fila_id' => 2, 'nombre' =>    'STES', 'color_id' =>    1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HLTD', 'ctrhr' => 'CLTD', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',                            'codigo' => '79100-0KK10', 'fila_id' => 2, 'nombre' =>    'STL1', 'color_id' =>    1, 'material_id' =>    2, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HHTD', 'ctrhr' => 'CHTD', 'ar' => 'AHTD', 'cantidad' =>    10, 'descripcion' => '',                        'codigo' => '79100-0KP40', 'fila_id' => 2, 'nombre' =>    'STHS', 'color_id' =>    1, 'material_id' =>    1, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HPTD', 'ctrhr' => 'CPTD', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => 'MATERIAL: PVC NEGRO',        'codigo' => '79100-0KQ80', 'fila_id' => 2, 'nombre' =>    'STP1', 'color_id' =>    1, 'material_id' =>    4, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HPTD', 'ctrhr' => 'CPTD', 'ar' => '-', 'cantidad' =>    10, 'descripcion' => '',       'codigo' => '', 'fila_id' => 2, 'nombre' =>    'SFLT', 'activo' => 0, 'color_id' =>    1, 'material_id' =>    4, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HETD1', 'ctrhr' => 'CETD', 'ar' => 'AETD', 'cantidad' =>    10, 'descripcion' => '	MATERIAL: CUERO NEGRO PERFORADO HILO DECK: GM20W-18250-00 (cono negro)', 'codigo' => '79100-0KY60-C2', 'fila_id' => 2, 'nombre' => 'STSS', 'color_id' =>    1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HHTD', 'ctrhr' => 'CHTD', 'ar' => 'AHTD', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '79100-AR010', 'fila_id' => 2, 'nombre' => 'STRS', 'activo' => 0, 'color_id' => 1, 'material_id' =>    1, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HETD', 'ctrhr' => 'CETD', 'ar' => 'AETD', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '79100-PHJ80', 'fila_id' => 2, 'nombre' => 'STTS', 'activo' => 0, 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HETD', 'ctrhr' => 'CETD', 'ar' => 'AETD', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '79100-SS510-D0', 'fila_id' => 2, 'nombre' => 'STGS-D0', 'activo' => 0, 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '-', 'cantidad' =>     10, 'descripcion' => '',       'codigo' => '79100-VR010', 'fila_id' => 5, 'nombre' => 'HRSH', 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => 'HETD', 'ctrhr' => 'CETD', 'ar' => 'AETD', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '79100-YP390-C0', 'fila_id' => 2, 'nombre' => 'STNS', 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => 'HETD', 'ctrhr' => 'CETD', 'ar' => 'AETD', 'cantidad' =>    10, 'descripcion' => '', 'codigo' => '79100-YP440-C1', 'fila_id' => 2, 'nombre' => 'STOS', 'activo' => 0, 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    1]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '	-', 'cantidad' =>    9, 'descripcion' => '',               'codigo' => '79210-VR010', 'fila_id' => 5, 'nombre' => 'HRDH-B', 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '	-', 'cantidad' =>    18, 'descripcion' => '',               'codigo' => '79210-VR011', 'fila_id' => 5, 'nombre' => 'HRDH-C', 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    0]);
        Modelos::create(['hr' => '-', 'ctrhr' => '-', 'ar' => '	-', 'cantidad' =>    5, 'descripcion' => '',               'codigo' => '79400-VR040', 'fila_id' => 5, 'nombre' => 'HSHS', 'color_id' => 1, 'material_id' =>    5, 'airbag' =>    0]);
    }
}
