<?php

namespace App\Http;

class EventosQr {
    public const REEMPLAZO_ETIQUETA = 'SE REEMPLAZÓ UNA ETIQUETA, ETIQUETA ANTERIOR EN INFO ADICIONAL';
    public const ETIQUETA_YA_COSIDA = 'LA ETIQUETA ESCANEADA YA FUE COSIDA';
    public const ETIQUETA_YA_VALIDADA = 'LA ETIQUETA ESCANEADA YA FUE VALIDADA';
    public const ETIQUETA_YA_CONTROLADA_QC = 'LA ETIQUETA YA FUE CONTROLADA PREVIAMENTE';
    public const MODELO_INCONSISTENTE = 'EL MODELO DEL KANBAN NO COINCIDE CON EL DE LA ETIQUETA';
    public const KANBAN_INCONSISTENTE = 'LA ETIQUETA NO CORRESPONDE AL KANBAN INGRESADO';
    public const MASCARA_INCONSISTENTE = 'LA MÁSCARA NO COINCIDE CON LA ETIQUETA ESCANEADA';
    public const ANULACION_ETIQUETA = 'ANULACIÓN ETIQUETA';
    public const MODELO_LADO_TIPO_COMPLETO = 'SE ALCANZO EL LIMITE DE DOLLY';
    public const RETRABAJO_PENDIENTE = 'TIENE RETRABAJOS PENDIENTES';
}
