<?php

namespace App\Http;

class EventosStrap {
    public const STRAP_INEXISTENTE = 'EL STRAP INDICADO NO EXISTE O YA FUE EGRESADO';
    public const FIFO_INCORRECTO_SECUENCIA = 'ERROR EN FIFO SECUENCIAL';
    public const MODELO_INCORRECTO = 'EL STRAP NO PERTENECE AL MODELO INDICADO';
    public const FIFO_INCORRECTO_LOTE = 'ERROR EN FIFO LOTE';
    public const DESCARGA_PARCIAL_REPOSICION = 'RETIRO REPOSICIÓN';
    public const DESCARGA_NORMAL = 'RETIRO STRAP';
    public const INGRESO_STRAP = 'INGRESO STRAP';
    public const ANULACION = 'ANULACION STRAP';
    public const REACTIVACION = 'REACTIVACION STRAP';
    public const MODIFICA_STRAP = 'MODIFICACION STRAP';
}
