<?php

namespace App\Http;

class LineasModelo {
    public const MODELOS = [
        'SFHG' => ['1', '2', '10'],
        'STL1' => ['4'],
        'STP1' => ['4'],
        'SFPA' => ['2'],
        'SFMR' => ['1'],
        'STHS' => ['3', '4'],
        'STES' => ['3', '4'],
        'STSS' => ['3', '4'],
        'STNS' => ['3', '4'],
        'SFLB' => ['2'],
        'SFLE' => ['2', '10'],
        'SFLC' => ['2', '10'],
        'SFLA' => ['2'],
        'SFPB' => ['2'],
        'SFPC' => ['2', '10'],
        'SFKQ' => ['1'],
        'SFKN' => ['1'],
        'SFJJ' => ['1'],
        'SFOR' => ['1'],
        'SFNG' => ['1'],
        'SFNJ' => ['1'],
        'SFBN' => ['1'],
        'SFEG' => ['1'],
        'SFTS' => ['1', '2'],
        'SFHP' => ['1'],
        'SFEP' => ['1'],
        'STOS' => ['4'],
        'HFLD-R' => ['11'],
        'HFLD-L' => ['11'],
        'HFLD' => ['11'],
        'HFHF' => ['11'],
        'HRSH' => ['11'],
        'HRDH' => ['11'],
        'HRDH-B' => ['11'],
        'HRDH-C' => ['11'],
        'HSHS' => ['11'],
        'HRSL' => ['11'],
        'HRDL-B' => ['11'],
        'HRDL-C' => ['11'],
        'HSLS' => ['11'],
        'HRTL-BR' => ['11'],
        'HRTL-BL' => ['11'],
        'HRTL-C' => ['11'],
        'S4LR'  => ['10'],
        'S4LF'  => ['10'],
    ];

    public const VEHICULOS = [
        'SFPA'    => 'C1A',
        'SFLA'    => 'C1B/C3B',
        'SFLB'    => 'C1C',
        'SFLC'    => 'C1E',
        'SFPB'    => 'C1F',
        'SFPC'    => 'C3Y/C1G',
        'SFEG'    => 'C3G',
        'STES'    => 'C3F',
        'SFLE'    => 'C3H',
        'STL1'    => 'C3H',
        'SFHG'    => 'C3J',
        'STHS'    => 'C3J',
        'SFHP'    => 'C3K',
        'STTS'    => 'C3N',
        'SFEP'    => 'C3Q',
        'SFNG'    => 'C3R',
        'STNS'    => 'C3R',
        'SFTG'    => 'C3N',
        'SFGG-D0' => 'C3R-D0',
        'SFTS'    => 'C3S',
        'STSS'    => 'C3S',
        'SFON'    => 'C3T',
        'SFOR'    => 'C3U',
        'STOS'    => 'C3U/C3T',
        'STP1'    => 'C3Y',
        'SFJK'    => 'C4G',
        'SFKQ'    => 'C4H',
        'SFBN'    => 'C4L',
        'SFNJ'    => 'C4R',
        'SFMR'    => 'C4S',
        'SFJJ'    => 'C4T',
        'SFKN'    => 'C4Y',
        'HFLD-L'    => 'I1A', //FR LH
        'HFLD-R'    => 'I1A', //FR RH
        'HFHF'    => 'I5A', //FR
        'HRDH-B'    => 'I5A', // (RR Doble)
        'HRDH-C'    => 'I5A', //(RR Doble)
        'HRSH'    => 'I5A', // (RR Simple)
        'HSHS'    => 'I5A', //(S-up)
        'HFLD'    => 'I5B',
        'HRDL'    => 'I5B',
        'HRDL-B'  => 'I5B', //(RR Doble)
        'HRDL-C'  => 'I5B', //(RR Doble)
        'HRSL'    => 'I5B', //(RR Simple)
        'HRTL'    => 'I5B', //(RR Triple)
        'HRTL-C'  => 'I5B', //(RR Triple)
        'HRTL-B'  => 'I5B', //(RR Triple)
        'HRTL-BL'  => 'I5B', //(RR Triple)
        'HRTL-BR'  => '',
        'HSLS'    => 'I5B', //(S-up)
        'SUNS'    => '',
        'SSFN'    => '',
        'SUJS'    => '',
        'SSBN'    => '',
        'SUBS'    => '',
        'SUKS'    => '',
        'SUMS'    => '',
        'SSLN'    => '',
        'S4LR'   => 'S4L',
        'S4LF'   => 'S4L',
    ];
}
